import turtle

my_turtle = turtle.Turtle()
# Change the shape of the turtle
my_turtle.shape("turtle")

for i in range(0, 1):
    # Draw a equilateral triangle
    my_turtle.left(60)
    my_turtle.forward(10)
    my_turtle.left(60)
    my_turtle.forward(20)
    my_turtle.left(60)
    my_turtle.forward(30)
    my_turtle.left(60)
    my_turtle.forward(40)
    my_turtle.left(60)
    my_turtle.forward(50)
    my_turtle.left(60)
    my_turtle.forward(60)
    my_turtle.left(60)
    my_turtle.forward(70)
    my_turtle.left(60)
    my_turtle.forward(80)
    my_turtle.left(60)
    my_turtle.forward(90)
    my_turtle.left(60)
    my_turtle.forward(100)
    my_turtle.left(60)
    my_turtle.forward(110)
    my_turtle.left(60)
    my_turtle.forward(120)
    my_turtle.left(60)
    my_turtle.forward(130)
    my_turtle.left(60)
    my_turtle.forward(140)
    my_turtle.left(60)
    my_turtle.forward(150)
    my_turtle.left(60)
    my_turtle.forward(160)
    my_turtle.left(60)
    my_turtle.forward(170)
    my_turtle.left(60)
    my_turtle.forward(180)
    my_turtle.left(60)
    my_turtle.forward(190)
    my_turtle.left(60)
    my_turtle.forward(200)
    my_turtle.left(60)
    my_turtle.forward(210)


turtle.done()
